import { z } from "zod";

export const EXHIBITOR_STATUSES = [
  "pending",
  "active",
  "Interested",
  "Reserved",
  "Not Interested",
  "Unable to attend",
  "Call Back",
  "No Answer",
  "Invalid Number",
  "Voice Mail",
  "Meeting Scheduled",
  "excluded",
] as const;

export const EXHIBITOR_BULK_STATUS_ACTIONS = [
  "active",
  "pending",
  "Interested",
  "Reserved",
  "Not Interested",
  "Unable to attend",
  "Call Back",
  "No Answer",
  "Invalid Number",
  "Voice Mail",
  "Meeting Scheduled",
  "excluded",
] as const;

export const eventExhibitorAdminSchema = z.object({
  first_name: z.string().trim().min(1, "First name is required"),
  last_name: z.string().trim().min(1, "Last name is required"),
  email: z.string().trim().email("Enter a valid email address"),
  phone: z.string().trim().optional().or(z.literal("")),
  work_phone: z.string().trim().optional().or(z.literal("")),
  business: z.string().trim().min(1, "Business name is required"),
  position: z.string().trim().optional().or(z.literal("")),
  website: z.string().trim().optional().or(z.literal("")),
  linkedin_user_profile: z.string().trim().optional().or(z.literal("")),
  facebook: z.string().trim().optional().or(z.literal("")),
  twitter: z.string().trim().optional().or(z.literal("")),
  instagram: z.string().trim().optional().or(z.literal("")),
  whatsapp_no: z.string().trim().optional().or(z.literal("")),
  zoom: z.string().trim().optional().or(z.literal("")),
  calendly: z.string().trim().optional().or(z.literal("")),
  youtube: z.string().trim().optional().or(z.literal("")),
  about_us: z.string().trim().optional().or(z.literal("")),
  stand_number: z.string().trim().optional().or(z.literal("")),
  stand_size: z.string().trim().optional().or(z.literal("")),
  stand_price: z.union([z.number(), z.string()]).optional().nullable(),
  discount: z.union([z.number(), z.string()]).optional().nullable(),
  charitable_amount: z.union([z.number(), z.string()]).optional().nullable(),
  exchange_amount: z.union([z.number(), z.string()]).optional().nullable(),
  exchange_services: z.boolean().optional().default(false),
  featured: z.boolean().optional().default(false),
  member_company_profile: z.boolean().optional().default(false),
  excluded_from_advertise: z.boolean().optional().default(false),
  enable_video_calling: z.boolean().optional().default(false),
  video_calling_software_provider: z.string().trim().optional().or(z.literal("")),
  video_call_url: z.string().trim().optional().or(z.literal("")),
  special_instructions: z.string().trim().optional().or(z.literal("")),
  referral_code: z.string().trim().optional().or(z.literal("")),
  referral_mstr_id: z.string().trim().optional().or(z.literal("")),
  referrer_from: z.string().trim().optional().or(z.literal("")),
  keynote_speech_topic: z.string().trim().optional().or(z.literal("")),
  is_webinars: z.boolean().optional().default(false),
  is_workshops: z.boolean().optional().default(false),
  is_business_presentation: z.boolean().optional().default(false),
  is_e_magazine: z.boolean().optional().default(false),
  is_newsletter: z.boolean().optional().default(false),
  visitor_notification_mail: z.boolean().optional().default(true),
  status: z.enum(EXHIBITOR_STATUSES).default("pending"),
});

export type EventExhibitorAdminInput = z.infer<typeof eventExhibitorAdminSchema>;
