/**
 * Ported from includes/class_event_block_setting.php's HardCode_data() — the default FAQ answer
 * text shown when an event hasn't filled in its own "About Show" custom answer for that
 * field_key yet. Trimmed of the legacy PHP's incidental leading/trailing whitespace; otherwise
 * verbatim (including the contact numbers/emails, which are genuinely reused boilerplate, not
 * this-event-specific — same as the legacy behaviour).
 *
 * Note: the legacy array key for "sustainability" was actually misspelled "sustainablity", which
 * meant that particular fallback silently never matched find_fields' field_key (spelled
 * correctly) and always rendered blank for events without their own custom answer. Keyed
 * correctly here — a deliberate, minor behaviour fix rather than a faithful bug-for-bug port.
 */
export const FAQ_HARDCODE_ANSWERS: Record<string, string> = {
  access: `Build-up

Shell scheme
Setup on a day before the event.Please Check with the organiser for timing details.

Space only stands
Setup on a day before the event.Please Check with the organiser for timing details.

If you need to transport goods to and from your stand please bring your own trolley as this will reduce loading and unloading times.

We recommend that you turn up on one day before the event to set up your stand. If you choose to set up on the morning of the event between 07:00 and 09:00hrs you will encounter queues and delays due to the volume of other exhibitors and visitors so please be patient.

Breakdown

On breakdown night, access to the hall is only available to contractors and other staff assisting in the breakdown of stands, once it is clear of visitors. Cars and small vans can be parked up at the venue from two hours before the event closes. Larger vehicles may not enter the site until two hours after the event closes.`,

  advertise: `+44 (0)1624 666105 events@findusonweb.com

There are extensive sponsorship and advertising opportunities available at The Venue. Please contact Carolyn or John for more information.`,

  animal: `Assistance dogs are welcome in the venue. If you do have advance notice, please inform your Event Manager.

Written consent must be obtained from the venue for any animals, wild or domestic (other than assistance animals), to be permitted on the premises.`,

  audio: `Please see Order forms section of the Manual or for pre-event orders & queries: T: +44 (0)1624 66610 or email events@findusonweb.com`,

  baby_changing: `Baby-changing facilities are available throughout the venue`,

  banking: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  business_services: `T: +44 (0)1624 666105
events@findusonweb.com

Please contact our team for information.`,

  catering: `Leith’s have exceptional experience in managing and delivering any culinary requirement for any amount of Staff. Our team is skilled at devising innovative, value-for-money options for any size of event or budget.

Whether it is a gala dinner for 20, cocktails and canapes for 500 or 1,000 packed lunches, our food and beverage professionals will deliver the finest culinary experience for you and your guests.`,

  chauffer: `T: +44 (0)1624 666105
events@findusonweb.com

Business Services provide an extensive range of chauffeured vehicles as well as executive and luxury coaches to get you about whilst visiting our venue.`,

  cleaning: `During the build-up and breakdown there will be cleaners in your event areas collecting any rubbish generated by the event. There will also be cleaners in your exhibition just before your event opens and during the open period.

Stand cleaning is done overnight on the Tuesday, Wednesday & Thursday Night of the show.`,

  cloakroom: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  convenience: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  nursery: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  deliveries: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  disabled: `Access
the Venue has been purposefully designed to allow unrestricted access for disabled visitors.

Parking
158 Disabled parking bays are located within close proximity of the venue. Spaces are available to blue badge holders only and badges must be displayed at all times. Parking for disabled visitors is charged at the normal rate. Access to the building from these bays is along walkways with a gradient of no more than 1:15 or lift (east end).

Within the Building
All public entrances allow for access by wheelchair via low gradient ramps or lifts. Lift control panels are located at a level which can be easily reached by someone in a wheelchair, and Braille or tactile buttons have also been installed.
All lifts have visual and voice indication of the floor reached and an intercom facility activated by an alarm button. The entire centre may be reached by lifts.
All stairs and ramps are fitted with handrails and balustrades.
All public corridors and passageways have a minimum clear width of 1200 mm.
Strong tactile differences in paving are provided to indicate hazardous areas. e.g. Dockedge indicated by cobble stone surface.
Door vision panels giving a zone of visibility between 900 mm and 1500 mm above floor level are provided on all public access doors.
Telephones are located at levels suitable for wheel chair users.
All reception counters, bars and self service counters and at least half the area where seating is provided is accessible to wheelchair users.
Self-service equipment such as cash machines and telephones are located at levels suitable to wheelchair users.
Pictographic signs and symbols have been used to guide people around the building.
Visitors with hearing and sight disabilities can gather information about the event, which they wish to visit by using:`,

  first_aid: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  florish: `T: +44 (0)1624 666105
events@findusonweb.com
www.findusonweb.com`,

  frieght: `For Freight and Onsite Handling Services please contact Tel +44 (0)1624 666105 or email events@findusonweb.com`,

  graphics: `Miscion are the official print supplier for the show and offer a complete range of signage and graphic solutions.

T: +44 (0)1624 666105
events@findusonweb.com
www.findusonweb.com

Vinyl graphics
Wide format printing
Posters
Printed foamex panels
Banners
Full installation service`,

  health: `It is the responsibility of the stand holder to ensure the health, safety and welfare of all employees, contractors and visitors as far as is reasonably practicable throughout your event.

It is recommended that the stand holders appoint a supervisor for the stand, with the specific responsibility for ensuring the health & safety of their staff and stand builders. It is compulsory that a Risk Assessment is completed for the stand and submitted to Dime Events.

Information Desks
T: +44 (0)1624 666105 - helpful staff are on hand to answer any questions you might have. You will also find a range of useful maps and leaflets.`,

  internet: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  it: `Pre-Event orders & queries: +44 (0)1624 666105
events@findusonweb.com
www.findusonweb.com

Using the latest technologies to enable Internet solutions that enhance exhibitor face-to-face sale opportunities.

High-speed Internet Access
Unrivalled Bandwidth > 200Mbps
Integrated Wireless Internet Access throughout the venue
Permanent data and telephone cabling within venue service ducts
Networking capabilities for over 8,500 PCs simultaneously
Web Streaming
Satellite and Broadcast Solutions
Bespoke demonstration, communication and presentation solutions
To order IT & Communications solutions simply complete our order form, or call the IT & Communications Service Delivery Team who can offer advice and discuss your bespoke event requirements.

All IT & Communications orders must be received 14 days before the first event build date to guarantee service delivery and avoid late order surcharges.`,

  lift: `Lift access is available to all levels throughout the venue as follows;

Lift access from level 0 for the access to the orange and purple car park entrances, the main venue toilet facilities, medic room and Business Services to level 1
Lift access to the Capital Suite -please see ICC Capital Suite
Lift access to the Platinum Suite -please see Platinum Suite
Lift access to the Gallery Rooms -please see Gallery Rooms`,

  lost_property: `T: +44 (0)1624 666105

Any lost property is managed by our Security Office, and will be kept for one month. If items have not been reclaimed within this period, they will be donated to a local charity, disposed or destroyed.

Passports, driving licenses, national insurance cards etc will be referred back to the relevant companies.

Unclaimed perishable goods are disposed of at the close of each day. (This includes any food i.e. bottles, food boxes, liquids etc)

If the owner can be identified, a note with details of the owner i.e. telephone number, date of the call, when the item will be picked up and any relevant info should be attached to the pink slip of the found book as well as a note on the item itself, In which case the date due for disposal shall be one calendar month after the date of the notice.`,

  parking: `Please contact our team for information on planning your journey by calling on +44 (0)1624 666105.`,

  pharmacy: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  photocoping: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  post: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  printing: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  public_service: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  shell_scheme_stand: `Shell scheme stands can be decorated on a day before the event.`,

  shell_scheme_health: `All shell scheme stands should send a copy of their Public Liability Insurance to Findusonweb Group. Along with the Compulsory Shell Scheme Construction Form.

When planning how to set up your shell scheme stand please ensure that all items are contained within the space and do not encroach into the gangways.

If you plan to change to anything mentioned in the Shell Scheme Construction Form then you will need to make your Findusonweb representative aware and our health and safety team. You will then need to complete a Freebuild Information Sheet.`,

  smoking: `Smoking is prohibited within the venue in accordance with UK Law. Smoking is permitted outside of the venue.`,

  space_freebuild: `If you are having a space only stand then there is some important information you need to know. Your contractors who are responsible for constructing your stand will be required to send Dime Events the following documents as soon as possible:

- Stand Plans showing dimensions and elevation
- Risk Assessment and Method Statement
- A copy of their Public Liability Insurance covering a minimum £5 million
- Completed CDM Compliance Sheet

Please feel free to contact one of our Health and safety team if you have any queries as they will be happy to help.

Please be aware that as of April 2015 your space only stand is classed as a CDM site (Construction, Design and Management Regulations), therefore the nominated Foreman will have overall control of what happens within the stand space.

You are also responsible to prepare a CDM Safety Project File, this should include:

- A brief description of the work carried out
- Any residual hazards which remain and how they have been dealt with
- Key structural information
- Safe working loads for floors and roofs, particularly where these may prohibit placing scaffolding or heavy machinery
- Hazardous materials used
- Information regarding the removal or dismantling of installed plant and equipment (e.g. any special arrangements for lifting, special instructions for dismantling etc.)
- Health and safety information about equipment provided for cleaning or maintaining the structure
- Information and as-built drawings of the structure, its plant and equipment (e.g. the means of safe access to and from service voids and fire doors)

SPACE ONLY SITES – FOREWORD

The build for space only stands will commence at 08:00 on the first build up day. Contractors should satisfy themselves that the positioning of the stand area is correct and, if necessary, conduct a site visit well in advance of the event. Any queries should be referred to the organisers as soon as possible before commencing construction.

CDM 2015

PLEASE NOTE: SPACE ONLY CONTRACTORS MUST FAMILIARISE THEMSELVES WITH THE CONFINES OF THE CONSTRUCTION (DESIGN & MANAGEMENT) 2015 REGULATIONS WHICH NOW GOVERN THE ENTERTAINMENT INDUSTRY.

You ARE required, under CDM, to submit a FULL site safety plan and also ensure that this is brought to, and produced on site. You should already be aware of the regulations currently in force within the construction industry, and a similar mode of operation will come into force in the whole of the entertainment industry from the 6th April 2015.

The attached Space Only Stand Check Sheet will need to be completed in the first instance and emailed directly to events@findusonweb.com. This also contains information on what should be submitted under CDM. Your stand build Space will ultimately become your own CDM site, and should be controlled as such.

It is highly likely that ALL persons entering the main CDM site will need to be inducted. This may be done remotely, with a declaration that all you employees have undertaken that induction. Please remember that this is not something which can be ‘addressed on the day’, CDM 2015 is statute, in other words, Law and should be obeyed as such.

FOREIGN CONTRACTORS

The regulations for CDM 2015 are Pan-European, which is partly the reason for them being introduced to the UK Entertainments industry. Overseas contractors are equally required, under law, to comply with them. ANY contractors NOT complying with the regulations in advance/on site, WILL be refused access or removed.

SPACE ONLY SITES – GENERAL

All space only sites must submit for approval, fully dimensioned drawings showing all proposed construction and elevations, together with risk assessments and method statements and Public Liability insurance. These should be submitted no later than 21 days before the event to Dime Events Ltd. Exhibitors and contractors should note that:

Please ensure the wall of the stand which is not backing onto another does not exceed a third of the length of the stand as to not obstruct the stand facing.

Any part of the wall above 2400mm must be suitably decorated and finished to a high standard. Branding is not allowed if overlooking an adjacent stand.

Space only exhibitors should note that their stands must comply with the Equality Act 2010, which supersedes the Disability Discrimination Act 2005, insofar as:

1. Reasonable adjustments made to services or premises to enable disabled people to access them.
2. Delivery of services by a reasonable alternative means provided
3. Where a stand requires a raised floor platform, consideration should be given to providing ramped access for wheelchair users.
4. Further advice can be found in the Accessible Exhibition Stand Handbook, issued by ESSA, available at the following link: http://www.aeo.org.uk/

Advertising or logos on the external walls of your stand is not permitted where they will interfere with another company’s exhibit.

There are specific requirements for staircases and handrails on multi-storey stands. Similarly, the larger stands which will be used to showcase services to an audience, may be required to have emergency exits, which, if opening outward, must be recessed so as not to open onto a gangway or thoroughfare, and must be fitted with Illuminated Exit Signs, in accordance with BS5499. All stand fittings must be constructed so as to present a clean appearance from gangways and adjoining stands.

If you are building a complex structure, you must also supply structural calculations and written confirmation from a structural engineer that the stand is fit for its purpose. A complex structure is defined as any form of construction of any height, which would normally be designed by an engineer and/or has, through a risk assessment, been found to present a significant risk. The following are always treated as complex structures:

- Stands over 4m in height, including the platform
- Double deck stands
- Suspended items of 400kg or over in weight
- Platforms and stages for public use and all platforms and stages over 0.6 metres in height
- Tiered seating structures
- Freebuild ceilings

All space only stands will be inspected and certified by an independent structural engineer on site. They will only be allowed to trade once the engineer is satisfied that the structure is safe and has provided certification.

It is the exhibitors / contractors responsibility to examine the site allocated in order to avoid adjustments to stand structure or displays. Although we give stand dimensions on the plan, if precise measurements are required we strongly advise a site survey.

Where appropriate, flooring ply or a platform must be used. All stand construction and displays must conform to the fire regulations, and be installed to the satisfaction of the venue owner and local authority. Exhibitors should note that stands deemed to be complex will require specific Local Authority approval, and must be agreed a minimum of 28 days before the event. Any structural engineering fees incurred in acquiring Local Authority approval must be borne by the exhibitor. If you have any queries on what are deemed complex structures, please contact John Fellows. Please note that sign off approval is given for stand plans/designs ONLY and are not a technical or structural sign off. No responsibility whatsoever will be accepted by the organisers or their representatives for the failure of exhibitors or their contractors to obtain the necessary information.

CONSTRUCTION HEIGHTS

Maximum stand construction heights in Olympia Exhibition Centre Grand Hall

WORKING AT HEIGHT REGULATIONS

A person is working ‘at height’ if there is a possibility of their being injured from falling, even if they are working at or below ground level.

The Working at Height Regulations refers to 'duty holders': employers, self-employed and employees. This includes all contractors and exhibitors (for example, when accessing areas above floor level to dress stands).

Duty holders’ responsibilities are to ensure that:

- no work is done at height if it is safe and reasonably practicable to do it other than at height
- ensure that the work is properly planned and organised, appropriately supervised and carried out in as safe a way as is reasonably practicable
- plans are in place for emergencies and rescue
- a suitable and sufficient risk assessment is carried out and the significant findings recorded and acted upon
- they do all that is reasonably practicable to prevent anyone falling
- all work at height takes account of conditions that could endanger health and safety
- those involved in work at height are trained and competent
- the place where work at height is done is safe
- equipment for work at height is appropriately inspected
- the risks from fragile surfaces are properly controlled
- the risks from falling objects are properly controlled

Equipment used for work at height must be suitable for the task. All equipment must be industrial quality (including ladders; domestic quality ladders are not permitted).

To conform to the Regulatory Reform (Fire Safety) Order 2005, all space only stands with store rooms must have clear vision panels in them, and doors on stands must not open into gangways, with the exception of emergency exit doors which must be recessed into the stand. ANY glass or clear vision doors on stands MUST have decals or logos on them to prevent them from being hazards.

All contractors and exhibitors are required to provide the following information:

The Space Only Stand Check Sheet in the first instance

CDM Project Safety File, which must contain, but is not limited to:

- Full technical stand plans, incorporating all dimensions, elevations and weight loadings. Please note that all height dimensions MUST include the floor platform.
- Stand visuals where possible
- Non generic risk assessment
- Non generic method statement
- Copy of your Public Liability Insurance, in date at the time of the event.
- Your Companies’ Health & Safety Policy Document and Statement
- Any other relevant information regarding any aspect of the design/construction phases.

We are here to help, and whilst stringent venue and H&S regulations and legislation has to be followed, we will do our best to assist with any queries you may have. Please just ask.`,

  space_only_stands: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  stationary_supplies: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  sustainability: `The Venue is 100% committed to tackling the challenges of sustainable development and operating as a responsible corporate entity. It is our policy to continuously evolve and implement practices that deliver economic security, social and environmental benefits.

In keeping with this, we are developing the following best practice initiatives:

Putting a sustainable business strategy in place for our direct in-house operations i.e. essentials such as lighting and heating
Setting a benchmark for our sector through the nature and rate of our sustainable development and innovations
Partnering with our clients and suppliers to develop and promote the most sustainable events possible
Reporting annually on our sustainability performance and achievements`,

  taxi: `Please contact our team for information by calling on +44 (0)1624 666105.

Please also see Chauffeur Services.`,

  telephone: `Exhibitor Services

Please contact our team for information by calling on +44 (0)1624 666105.`,

  toilet: `Please contact our team for information by calling on +44 (0)1624 666105.`,

  traffic: `Please contact our team for information by calling on +44 (0)1624 666105.`,
};
